"""Zero-Trust Lab scenario engine.

A scenario is a natural-language situation ("analyst blocked from restricted
billing, engineer delegates scoped read"). The planner transforms it into a
concrete blueprint: agentic steps ``{agent, action, resource}``, generated
governance policies, and an optional delegation. Blueprints are staged as
``ScenarioPlan`` rows (status ``proposed``), previewed against an in-memory
policy evaluation that persists nothing, and only after explicit approval are
the generated policies created in the store and the steps enforced through the
signed gateway.
"""

from __future__ import annotations

import json
import re
import time

from . import models
from .config import get_settings
from .policy import condition_matches

settings = get_settings()

MART_DEMOGRAPHICS = "urn:li:dataset:(urn:li:dataPlatform:sqlite,healthcare.main.mart_demographics,PROD)"
MART_BILLING = "urn:li:dataset:(urn:li:dataPlatform:sqlite,healthcare.main.mart_billing,PROD)"
RAW_PATIENTS = "urn:li:dataset:(urn:li:dataPlatform:sqlite,healthcare.main.raw_patients,PROD)"
STAGING_PATIENTS = "urn:li:dataset:(urn:li:dataPlatform:sqlite,healthcare.main.staging_patients,PROD)"
ML_MODEL = "urn:li:mlModel:(urn:li:dataPlatform:mlflow,churn_model,PROD)"
ML_PREDICTIONS = "urn:li:dataset:(urn:li:dataPlatform:bigquery,ml.churn_predictions,PROD)"

# Policies the scenario engine generates. Names carry the ``lab-`` prefix so the
# lab can clean them up on reset without touching the project's seed policies.
POLICY_TEMPLATES: dict[str, dict] = {
    "lab-allow-delegated-restricted-read": {
        "description": "Generated by the lab: restricted datasets may be read only through an active, dataset-scoped delegation.",
        "effect": "allow", "actions": ["read", "query"],
        "conditions": [
            {"path": "delegation.active", "op": "is_true"},
            {"path": "delegation.dataset_scope_match", "op": "is_true"},
            {"path": "target.data_classification", "op": "eq", "value": "restricted"},
        ],
        "order": 44,
    },
    "lab-require-delegation-for-restricted": {
        "description": "Generated by the lab: reads of restricted data without an active delegation are denied for non-privileged agents.",
        "effect": "deny", "actions": ["read", "query"],
        "conditions": [
            {"path": "target.data_classification", "op": "eq", "value": "restricted"},
            {"path": "agent.reputation_tier", "op": "lt", "value": "privileged"},
            {"path": "delegation.active", "op": "is_false"},
        ],
        "order": 45,
    },
    "lab-deny-pii-transforms-below-elevated": {
        "description": "Generated by the lab: transforms of sensitive or restricted data require an elevated tier.",
        "effect": "deny", "actions": ["transform"],
        "conditions": [
            {"path": "target.data_classification", "op": "in", "value": ["sensitive", "restricted"]},
            {"path": "agent.reputation_tier", "op": "lt", "value": "elevated"},
        ],
        "order": 46,
    },
    "lab-allow-transform-sensitive-elevated": {
        "description": "Generated by the lab: elevated+ agents may transform sensitive data.",
        "effect": "allow", "actions": ["transform"],
        "conditions": [
            {"path": "agent.reputation_tier", "op": "gte", "value": "elevated"},
            {"path": "target.data_classification", "op": "in", "value": ["public", "sensitive"]},
        ],
        "order": 49,
    },
    "lab-allow-deploy-ml-models": {
        "description": "Generated by the lab: elevated+ agents may deploy models in the ML domain.",
        "effect": "allow", "actions": ["deploy"],
        "conditions": [
            {"path": "agent.reputation_tier", "op": "gte", "value": "elevated"},
            {"path": "target.domain", "op": "eq", "value": "ML"},
            {"path": "target.data_classification", "op": "in", "value": ["public", "sensitive"]},
        ],
        "order": 56,
    },
    "lab-deny-deploy-below-elevated": {
        "description": "Generated by the lab: deploying models requires an elevated tier.",
        "effect": "deny", "actions": ["deploy"],
        "conditions": [
            {"path": "agent.reputation_tier", "op": "lt", "value": "elevated"},
        ],
        "order": 57,
    },
}


def _policy(name: str, note: str = "") -> dict:
    p = dict(POLICY_TEMPLATES[name])
    p["name"] = name
    if note:
        p["description"] = f"{p['description']} {note}".strip()
    return p


PREDEFINED_SCENARIOS = [
    {
        "id": "scn_billing",
        "name": "Restricted patient billing access",
        "description": "A standard analyst is blocked from the restricted billing mart, a privileged engineer delegates scoped read access, and the analyst succeeds strictly inside scope.",
        "objective": (
            "kay-analyst reads aggregated patient demographics from the healthcare mart, is "
            "blocked from the restricted patient billing mart, then priya-data-engineer "
            "delegates read access to the billing mart within an exact scope. kay-analyst "
            "succeeds within that scope but is blocked from writes."
        ),
        "agents": ["ag_analyst", "ag_engineer"],
        "blueprint": {
            "steps": [
                {"agent": "ag_analyst", "action": "read", "resource": MART_DEMOGRAPHICS,
                 "expect": "allow", "note": "kay-analyst reads aggregated patient demographics."},
                {"agent": "ag_analyst", "action": "read", "resource": MART_BILLING,
                 "expect": "deny", "note": "kay-analyst tries to read restricted billing — denied until delegation."},
                {"agent": "ag_analyst", "action": "read", "resource": MART_BILLING, "delegation": True,
                 "expect": "allow", "note": "kay-analyst reads billing under the scoped delegation."},
                {"agent": "ag_analyst", "action": "write", "resource": MART_BILLING, "delegation": True,
                 "expect": "deny", "note": "write is outside the delegated actions — scope is enforced."},
            ],
            "policies": [
                _policy("lab-allow-delegated-restricted-read", "for the billing mart."),
                _policy("lab-require-delegation-for-restricted", "for the billing mart."),
            ],
            "delegation": {
                "delegator_id": "ag_engineer", "delegatee_id": "ag_analyst",
                "scope": {"actions": ["read", "query"], "datasets": [MART_BILLING], "domains": []},
                "max_depth": 1,
            },
        },
    },
    {
        "id": "scn_pii",
        "name": "PII transform workflow",
        "description": "A standard analyst is blocked from transforming raw PII patient records; an elevated ML engineer transforms staging data; a privileged engineer writes the curated mart.",
        "objective": (
            "leo-ml-engineer transforms sensitive patient staging data into features, "
            "priya-data-engineer writes the curated demographics mart, and kay-analyst "
            "is blocked from transforming raw PII patient records."
        ),
        "agents": ["ag_analyst", "ag_engineer", "ag_ml_engineer"],
        "blueprint": {
            "steps": [
                {"agent": "ag_analyst", "action": "transform", "resource": RAW_PATIENTS,
                 "expect": "deny", "note": "kay-analyst (standard) is blocked from transforming raw PII."},
                {"agent": "ag_ml_engineer", "action": "transform", "resource": STAGING_PATIENTS,
                 "expect": "allow", "note": "leo-ml-engineer (elevated) transforms sensitive staging data."},
                {"agent": "ag_engineer", "action": "write", "resource": MART_DEMOGRAPHICS,
                 "expect": "allow", "note": "priya-data-engineer (privileged) writes the curated mart."},
            ],
            "policies": [
                _policy("lab-deny-pii-transforms-below-elevated", "for patient PII."),
                _policy("lab-allow-transform-sensitive-elevated", "for patient staging features."),
            ],
            "delegation": None,
        },
    },
    {
        "id": "scn_deploy",
        "name": "Cross-domain ML deployment",
        "description": "An elevated ML engineer deploys a model in the ML domain; a privileged engineer writes predictions back; a standard analyst is blocked from deploying.",
        "objective": (
            "leo-ml-engineer deploys the churn model in the ML domain, priya-data-engineer "
            "writes predictions to the feature store, and kay-analyst is blocked from deploying models."
        ),
        "agents": ["ag_analyst", "ag_engineer", "ag_ml_engineer"],
        "blueprint": {
            "steps": [
                {"agent": "ag_ml_engineer", "action": "deploy", "resource": ML_MODEL,
                 "expect": "allow", "note": "leo-ml-engineer (elevated) deploys the model in the ML domain."},
                {"agent": "ag_analyst", "action": "deploy", "resource": ML_MODEL,
                 "expect": "deny", "note": "kay-analyst (standard) is blocked from deploying models."},
                {"agent": "ag_engineer", "action": "write", "resource": ML_PREDICTIONS,
                 "expect": "allow", "note": "priya-data-engineer (privileged) writes predictions back."},
            ],
            "policies": [
                _policy("lab-allow-deploy-ml-models"),
                _policy("lab-deny-deploy-below-elevated"),
            ],
            "delegation": None,
        },
    },
]


def list_predefined() -> list[dict]:
    return [
        {
            "id": s["id"], "name": s["name"], "description": s["description"],
            "objective": s["objective"], "agents": list(s["agents"]),
            "steps": s["blueprint"]["steps"],
        }
        for s in PREDEFINED_SCENARIOS
    ]


def get_predefined(scenario_id: str) -> dict | None:
    return next((s for s in PREDEFINED_SCENARIOS if s["id"] == scenario_id), None)


# ---------------------------------------------------------------------------
# Planning: scenario text -> blueprint (agentic steps, policies, delegation)
# ---------------------------------------------------------------------------

_AGENT_NAMES = {
    "ag_analyst": ["kay"],
    "ag_engineer": ["priya"],
    "ag_ml_engineer": ["leo"],
}
_AGENT_ROLE_IDS = {
    "ag_ml_engineer": ["ml-engineer", "ml_engineer", "ml engineer", "ml-engineers"],
    "ag_engineer": ["data-engineer", "data_engineer", "data engineer", "data-engineers"],
    "ag_analyst": ["analyst"],
}
_AGENT_ROLE_WORDS = {
    "ag_analyst": ["analyst"],
    "ag_ml_engineer": ["ml"],
    "ag_engineer": ["engineer"],
}


def _agent_matches(sentence: str) -> list[str]:
    lower = sentence.lower()
    found: list[str] = []
    # 1. proper names are decisive
    for aid, names in _AGENT_NAMES.items():
        if any(n in lower for n in names):
            found.append(aid)
    # 2. hyphenated roles; consume matched phrases so a bare role word such as
    #    "engineer" can't be matched again inside "ml-engineer"
    remaining = lower
    for aid, roles in _AGENT_ROLE_IDS.items():
        if aid in found or not any(r in lower for r in roles):
            continue
        found.append(aid)
        for r in roles:
            remaining = remaining.replace(r, " ")
    # 3. bare role words on the residual text
    for aid, roles in _AGENT_ROLE_WORDS.items():
        if aid not in found and any(r in remaining for r in roles):
            found.append(aid)
    return found


def _parse_agents(objective: str, agents_hint: list[str] | None) -> list[str]:
    ids: list[str] = []
    for a in agents_hint or []:
        if a not in ids:
            ids.append(a)
    for aid in _agent_matches(objective):
        if aid not in ids:
            ids.append(aid)
    return ids or ["ag_analyst"]


def _role(agent_id: str) -> str:
    from agents.registry import get_agent_spec

    try:
        return get_agent_spec(agent_id)["role"]
    except (KeyError, Exception):  # noqa: BLE001
        return {"ag_analyst": "analyst", "ag_engineer": "engineer", "ag_ml_engineer": "ml_engineer"}.get(agent_id, "analyst")


def _catalog(db) -> list[dict]:
    rows = db.query(models.DataHubEntity).all()
    return [
        {"urn": e.urn, "name": e.name, "domain": e.domain,
         "data_classification": e.data_classification, "description": e.description}
        for e in rows
    ]


def _pick_agent(sentence: str, agents: list[str]) -> str:
    for aid in _agent_matches(sentence):
        if aid in agents:
            return aid
    return agents[0]


_MATCH_STOP = {"from", "for", "into", "via", "main", "the", "a", "an", "to", "of", "in", "on", "with", "and", "or"}


def _norm_token(w: str) -> str:
    w = w.lower()
    if len(w) > 3 and w.endswith("ies"):
        return w[:-3] + "y"
    if len(w) > 3 and w.endswith("s") and not w.endswith("ss"):
        return w[:-1]
    return w


def _match_tokens(text: str) -> set[str]:
    from agents.planner import _tokens

    return {_norm_token(t) for t in _tokens(text) if _norm_token(t) not in _MATCH_STOP}


def _match_entity_local(objective: str, entities: list[dict], domains: list[str]) -> str | None:
    """Catalog match that weights the entity NAME over its description, with
    singular/plural normalization and noise-word removal, so a sentence about
    "raw patient records" picks ``raw_patients`` rather than a view whose name
    merely shares a generic word like ``from``."""
    words = _match_tokens(objective)
    best, best_score = None, 0
    for ent in entities:
        name = _match_tokens(ent["name"])
        desc = _match_tokens(f"{ent.get('description', '')} {ent.get('domain', '')}")
        overlap = len(words & name) * 3 + len(words & desc)
        if ent.get("domain") in domains:
            overlap += 1
        if overlap > best_score:
            best, best_score = ent["urn"], overlap
    return best if best_score >= 3 else None


def _rule_steps(db, objective: str, agents: list[str]) -> list[dict]:
    from agents.planner import _action_type, _ROLE_DEFAULT

    entities = _catalog(db)
    sentences = [s.strip() for s in re.split(r"[.;\n]+", objective) if s.strip()]
    if not sentences:
        sentences = [objective]
    steps: list[dict] = []
    seen: set[tuple] = set()
    for s in sentences:
        agent = _pick_agent(s, agents)
        role = _role(agent)
        action = _action_type(s, role)
        urn = _match_entity_local(s, entities, _domains(agent)) or _ROLE_DEFAULT.get(role)
        ent = db.get(models.DataHubEntity, urn)
        key = (agent, action, urn)
        if key in seen:
            continue
        seen.add(key)
        steps.append({
            "agent": agent, "action": action, "resource": urn,
            "domain": ent.domain if ent else "",
            "classification": ent.data_classification if ent else "public",
            "note": s[:160],
        })
    return steps


def _domains(agent_id: str) -> list[str]:
    from agents.registry import get_agent_spec

    try:
        return get_agent_spec(agent_id)["domains"]
    except (KeyError, Exception):  # noqa: BLE001
        return []


def _llm_steps(db, objective: str, agents: list[str]) -> list[dict] | None:
    """Best-effort LLM step extraction; None degrades to the rule translator."""
    if not settings.llm_model:
        return None
    try:
        import litellm

        entities = _catalog(db)
        catalog = "\n".join(
            f"- URN {e['urn']} | name: {e.get('name', '')} | domain: {e.get('domain', '')} | "
            f"classification: {e.get('data_classification', 'public')}"
            for e in entities[:60]
        )
        system = (
            "You extract governed agent actions from a scenario. The ONLY resources "
            "are the catalog items below; you MUST use their exact URNs.\n\n"
            "{catalog}\n\n"
            'Return ONLY JSON: {{"steps": [{{"agent": "<agent id from {agents}>", '
            '"action": "<read|query|transform|write|ingest|deploy>", '
            '"resource": "<exact catalog URN>", "note": "<one-line rationale>"}}]}}.'.format(
                catalog=catalog, agents=agents)
        )
        user = f"Scenario: {objective}"
        resp = litellm.completion(
            model=settings.llm_model,
            messages=[{"role": "system", "content": system}, {"role": "user", "content": user}],
            api_base=settings.llm_base_url or None,
            api_key=settings.llm_api_key or None,
            temperature=settings.llm_temperature,
            timeout=30,
        )
        text = resp.choices[0].message.content or ""
        start, end = text.find("{"), text.rfind("}")
        if start == -1 or end <= start:
            return None
        payload = json.loads(text[start:end + 1])
        raw_steps = payload.get("steps", [])
        valid = [s for s in raw_steps if isinstance(s, dict)]
        steps = []
        urns = {e["urn"] for e in entities}
        for s in valid[:8]:
            agent = s.get("agent", "")
            action = s.get("action", "")
            resource = s.get("resource", "")
            if agent not in agents or action not in models.ACTION_TYPES or resource not in urns:
                continue
            ent = db.get(models.DataHubEntity, resource)
            steps.append({
                "agent": agent, "action": action, "resource": resource,
                "domain": ent.domain if ent else "",
                "classification": ent.data_classification if ent else "public",
                "note": (s.get("note") or "")[:160],
            })
        return steps or None
    except Exception:  # noqa: BLE001
        return None


def _derive_policies(steps: list[dict]) -> list[dict]:
    policies: list[dict] = []
    actions = {s["action"] for s in steps}
    if any(s.get("classification") == "restricted" for s in steps):
        policies.append(_policy("lab-allow-delegated-restricted-read"))
        policies.append(_policy("lab-require-delegation-for-restricted"))
    if "transform" in actions:
        policies.append(_policy("lab-deny-pii-transforms-below-elevated"))
        policies.append(_policy("lab-allow-transform-sensitive-elevated"))
    if "deploy" in actions:
        policies.append(_policy("lab-allow-deploy-ml-models"))
        policies.append(_policy("lab-deny-deploy-below-elevated"))
    return policies


def _derive_delegation(objective: str, steps: list[dict]) -> dict | None:
    if "delegat" not in objective.lower():
        return None
    restricted = [s for s in steps if s.get("classification") == "restricted"]
    datasets = [s["resource"] for s in restricted] or [s["resource"] for s in steps[:1]]
    return {
        "delegator_id": "ag_engineer", "delegatee_id": "ag_analyst",
        "scope": {"actions": ["read", "query"], "datasets": datasets, "domains": []},
        "max_depth": 1,
    }


def _flag_delegated_steps(steps: list[dict], delegation: dict | None) -> list[dict]:
    if not delegation:
        return steps
    scope = delegation["scope"]
    actions = scope.get("actions", [])
    datasets = set(scope.get("datasets", []))
    delegatee = delegation["delegatee_id"]
    for s in steps:
        if s["agent"] == delegatee and s["resource"] in datasets and s["action"] in actions:
            s["delegation"] = True
    return steps


def _custom_blueprint(db, objective: str, agents_hint: list[str] | None) -> dict:
    agents = _parse_agents(objective, agents_hint)
    steps = _llm_steps(db, objective, agents) or _rule_steps(db, objective, agents)
    policies = _derive_policies(steps)
    delegation = _derive_delegation(objective, steps)
    steps = _flag_delegated_steps(steps, delegation)
    return {"agents": agents, "steps": steps, "policies": policies, "delegation": delegation}


def transform(db, scenario_id: str = "", objective: str = "", agents_hint: list[str] | None = None) -> dict:
    """Transform a scenario (predefined or free text) into a proposed plan."""
    if scenario_id:
        scenario = get_predefined(scenario_id)
        if scenario is None:
            raise ValueError(f"unknown scenario: {scenario_id}")
        for step in scenario["blueprint"]["steps"]:
            if db.get(models.DataHubEntity, step["resource"]) is None:
                raise ValueError(
                    f"scenario {scenario_id} references {step['resource']} which is not in the catalog")
        blueprint = dict(scenario["blueprint"])
        blueprint.setdefault("agents", list(scenario.get("agents") or []))
        name = scenario["name"]
        effective_objective = scenario["objective"]
    else:
        if not objective or not objective.strip():
            raise ValueError("a custom scenario requires an objective")
        blueprint = _custom_blueprint(db, objective, agents_hint)
        name = objective.strip()[:64]
        effective_objective = objective.strip()

    plan = models.ScenarioPlan(
        id=f"plan-{int(time.time_ns()) % 10**14}",
        scenario_id=scenario_id, name=name, objective=effective_objective,
        status="proposed", blueprint=json.dumps(blueprint),
    )
    db.add(plan)
    db.commit()
    db.refresh(plan)
    return {"plan_id": plan.id, "name": plan.name, "status": plan.status,
            "scenario_id": plan.scenario_id, "blueprint": blueprint}


# ---------------------------------------------------------------------------
# Preview: in-memory policy simulation (nothing persisted)
# ---------------------------------------------------------------------------

def _policy_dicts(db) -> list[dict]:
    rows = db.query(models.Policy).filter(models.Policy.enabled.is_(True)).all()
    return [
        {"name": p.name, "effect": p.effect, "actions": json.loads(p.actions or "[]"),
         "conditions": json.loads(p.conditions or "[]"), "order": p.order, "generated": False}
        for p in rows
    ]


def _proposed_policy_dicts(blueprint: dict) -> list[dict]:
    return [
        {"name": p["name"], "effect": p["effect"], "actions": p["actions"],
         "conditions": p["conditions"], "order": p["order"], "generated": True}
        for p in blueprint.get("policies", [])
    ]


def _simulate_input(db, agent, action_type: str, resource: str, delegation_spec: dict | None) -> dict:
    entity = db.get(models.DataHubEntity, resource)
    granted = json.loads(agent.granted_domains or "[]")
    effective_tier = agent.tier
    delegator_id = ""
    delegation_active = bool(delegation_spec)
    depth, max_depth = 0, 0
    dataset_scope_match, action_in_scope = False, True
    if delegation_spec:
        delegator = db.get(models.Agent, delegation_spec.get("delegator_id", ""))
        if delegator is not None:
            effective_tier = delegator.tier
            delegator_id = delegator.id
        scope = delegation_spec.get("scope", {})
        granted = list(dict.fromkeys(granted + scope.get("domains", [])))
        max_depth = delegation_spec.get("max_depth", 1)
        depth = delegation_spec.get("depth", 0)
        action_in_scope = action_type in scope.get("actions", [])
        datasets = scope.get("datasets", [])
        dataset_scope_match = bool(datasets) and resource in datasets
    return {
        "agent": {"id": agent.id, "reputation_tier": effective_tier, "trust_score": agent.trust_score,
                  "status": agent.status, "granted_domains": granted},
        "action": {"type": action_type, "resource": resource},
        "target": {
            "entity_type": entity.type if entity else "dataset",
            "domain": entity.domain if entity else "",
            "data_classification": entity.data_classification if entity else "public",
            "owner_team": entity.owner_team if entity else "",
        },
        "delegation": {
            "active": delegation_active, "depth": depth, "max_depth": max_depth,
            "delegator_id": delegator_id, "dataset_scope_match": dataset_scope_match,
            "action_in_scope": action_in_scope,
        },
    }


def _evaluate_policy_dicts(policy_dicts: list[dict], input_data: dict) -> dict:
    for p in sorted(policy_dicts, key=lambda p: p["order"]):
        actions = p.get("actions") or []
        if actions and input_data["action"]["type"] not in actions:
            continue
        conditions = p.get("conditions") or []
        if conditions and not all(condition_matches(c, input_data) for c in conditions):
            continue
        return {"allow": p["effect"] == "allow", "reason": p["name"],
                "policy": p["name"], "generated": p.get("generated", False)}
    return {"allow": False, "reason": "no matching policy (default deny)",
            "policy": "default-deny", "generated": False}


def preview(db, plan: models.ScenarioPlan) -> dict:
    """Simulate the enforced decisions for every step using the seed policies
    plus the proposed lab policies — all in memory, nothing written."""
    blueprint = json.loads(plan.blueprint)
    policy_dicts = _policy_dicts(db) + _proposed_policy_dicts(blueprint)
    delegation_spec = blueprint.get("delegation")

    predictions = []
    for idx, step in enumerate(blueprint.get("steps", [])):
        agent = db.get(models.Agent, step["agent"])
        spec = delegation_spec if step.get("delegation") else None
        if agent is None:
            predictions.append({"index": idx, "error": f"unknown agent {step['agent']}"})
            continue
        input_data = _simulate_input(db, agent, step["action"], step["resource"], spec)
        # Mirror the gateway's delegation scope gate, which precedes policy.
        if spec and not input_data["delegation"]["action_in_scope"]:
            decision = {"allow": False, "reason": f"action outside delegated scope: {step['action']}",
                        "policy": "delegation.scope", "generated": False}
        else:
            decision = _evaluate_policy_dicts(policy_dicts, input_data)
        entity = db.get(models.DataHubEntity, step["resource"])
        predictions.append({
            "index": idx,
            "agent": step["agent"], "action": step["action"], "resource": step["resource"],
            "resource_name": entity.name if entity else step["resource"],
            "domain": step.get("domain") or (entity.domain if entity else ""),
            "classification": step.get("classification") or (entity.data_classification if entity else ""),
            "delegation": bool(step.get("delegation")),
            "note": step.get("note", ""),
            "expected": step.get("expect"),
            "predicted": "allow" if decision["allow"] else "deny",
            "reason": decision["reason"], "policy": decision["policy"],
            "policy_generated": decision["generated"],
        })

    return {"plan_id": plan.id, "status": plan.status, "predictions": predictions,
            "proposed_policies": blueprint.get("policies", []),
            "delegation": blueprint.get("delegation")}


# ---------------------------------------------------------------------------
# Approval: persist generated policies (idempotent) + cleanup
# ---------------------------------------------------------------------------

def persist_policies(db, blueprint: dict, scenario_id: str) -> list[str]:
    created: list[str] = []
    for p in blueprint.get("policies", []):
        existing = db.query(models.Policy).filter(models.Policy.name == p["name"]).first()
        if existing is not None:
            existing.description = p["description"]
            existing.effect = p["effect"]
            existing.actions = json.dumps(p["actions"])
            existing.conditions = json.dumps(p["conditions"])
            existing.order = p["order"]
            existing.enabled = True
            created.append(existing.name)
            continue
        policy = models.Policy(
            id=f"pol-{abs(hash(p['name'])) % 100000:05d}",
            name=p["name"], description=p["description"], effect=p["effect"],
            actions=json.dumps(p["actions"]), conditions=json.dumps(p["conditions"]),
            order=p["order"], enabled=True,
        )
        db.add(policy)
        created.append(policy.name)
    return created


def cleanup_lab_policies(db, scenario_id: str = "") -> int:
    q = db.query(models.Policy).filter(models.Policy.name.like("lab-%"))
    rows = q.all()
    count = len(rows)
    for row in rows:
        db.delete(row)
    return count


def restore_demo_agents(db) -> None:
    from .models import tier_for_score
    from .seed import DEMO_AGENTS

    for spec in DEMO_AGENTS:
        agent = db.get(models.Agent, spec["id"])
        if agent is None:
            continue
        agent.status = "active"
        agent.trust_score = spec["trust_score"]
        agent.tier = tier_for_score(spec["trust_score"])
        agent.granted_domains = json.dumps(spec["domains"])
        db.query(models.Violation).filter(models.Violation.agent_id == agent.id).delete(
            synchronize_session=False)


def reset_lab(db) -> dict:
    from .hashchain import append_event

    removed = cleanup_lab_policies(db)
    restore_demo_agents(db)
    append_event(db, "lab.reset", actor_id="console", subject="zero-trust-lab",
                 payload={"policies_removed": removed, "agents_restored": True},
                 decision="allow")
    db.commit()
    return {"policies_removed": removed, "agents_restored": True}
